DROP FUNCTION IF EXISTS createcareer;
DROP FUNCTION IF EXISTS updatecareer;
DROP FUNCTION IF EXISTS deletecareer;
DROP FUNCTION IF EXISTS getcareer;
DROP FUNCTION IF EXISTS getcareers;
DROP FUNCTION IF EXISTS careerexists;