DROP FUNCTION IF EXISTS createproject;
DROP FUNCTION IF EXISTS getprojects;
DROP FUNCTION IF EXISTS getprojectbyid;
DROP FUNCTION IF EXISTS updateproject;
DROP FUNCTION IF EXISTS assignpersonproject;
DROP FUNCTION IF EXISTS getpersonsproject;
DROP FUNCTION IF EXISTS getstudentsproject;
DROP FUNCTION IF EXISTS getpersonsnotinproject;
DROP FUNCTION IF EXISTS getprojectstudent;