DROP FUNCTION IF EXISTS createuser;
DROP FUNCTION IF EXISTS getpassword;
DROP FUNCTION IF EXISTS getusers;
DROP FUNCTION IF EXISTS userEmailExists;
DROP FUNCTION IF EXISTS updateResetToken;
DROP FUNCTION IF EXISTS validateToken;
DROP FUNCTION IF EXISTS updatePassword;
