INSERT INTO public.campus(campus_code,name,status) VALUES 
(45,'Acosta',true),
(4,'Alajuela',true),
(35,'Atenas',true),
(29,'Buenos Aires',true),
(8,'Cañas',true),
(3,'Cartago',true),
(10,'Ciudad Neilly',true),
(42,'Desamparados',true),
(16,'Guápiles',true),
(34,'Heredia',true),
(22,'Jicaral',true),
(23,'La Cruz',true),
(33,'La Reforma',true),
(26,'Liberia',true),
(12,'Limón',true),
(37,'Monteverde',true),
(7,'Nicoya',true),
(17,'Orotina',true),
(11,'Osa',true),
(6,'Palmares',true),
(43,'Los Chiles',true),
(13,'San Isidro Pérez Zeledón',true),
(40,'Puerto Jiménez',true),
(9,'Puntarenas',true),
(20,'Puriscal',true),
(2,'Quepos',true),
(5,'San Carlos',true),
(1,'San José',true),
(25,'San Marcos',true),
(21,'San Vito',true),
(32,'Santa Cruz',true),
(18,'Sarapiquí',true),
(14,'Siquirres',true),
(44,'Talamanca',true),
(36,'Tilarán',true),
(27,'Turrialba',true),
(24,'Upala',true);